[profile.default]
    src = "src"
    out = "out"
    libs = ["lib"]
    evm_version = 'paris'
    optimizer = true
    via_ir = true

remappings = [
    '@layerzerolabs/=node_modules/@layerzerolabs/',
    '@openzeppelin/=node_modules/@openzeppelin/',
]

# LZ does not have v2 endpoints on goerli
[rpc_endpoints]
    sepolia = "https://eth-sepolia.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
    arbitrum_sepolia = "https://arb-sepolia.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
    mainnet = "https://eth-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
    base_sepolia = "https://base-sepolia.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
    base = "https://base-mainnet.infura.io/v3/${INFURA_API_KEY}"

[etherscan]
    arbitrum_sepolia = { key = "${ARBISCAN_API_KEY}" }
    sepolia = { key = "${ETHERSCAN_API_KEY}" }
    mainnet = { key = "${ETHERSCAN_API_KEY}" }
    base_sepolia = { key = "${BASESCAN_API_KEY}" }
    base = { key = "${BASESCAN_API_KEY}" }
    
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
